#ifndef __CONFIG_S5P6818_H
#define __CONFIG_S5P6818_H

#define CONFIG_SYS_MAXARGS		16
#define CONFIG_SYS_CBSIZE		1024
#define CONFIG_ENV_SIZE			(128 << 10)
#define CONFIG_SYS_MAX_FLASH_BANKS	0
#define CONFIG_SKIP_LOWLEVEL_INIT


#define CONFIG_EXTRA_ENV_SETTINGS	"fdt_high=0xffffffffffffffff"

/* using SRAM for SPL init here */
#define CONFIG_SYS_INIT_RAM_ADDR	0xffff0000
#define CONFIG_SYS_INIT_RAM_SIZE	0x10000  /* 64 KiB */

#define CONFIG_SYS_INIT_SP_OFFSET \
		(CONFIG_SYS_INIT_RAM_SIZE - GENERATED_GBL_DATA_SIZE)
#define CONFIG_SYS_INIT_SP_ADDR \
		(CONFIG_SYS_INIT_RAM_ADDR + CONFIG_SYS_INIT_SP_OFFSET)

#define CONFIG_NR_DRAM_BANKS		1
#define CONFIG_SYS_SDRAM_BASE		0x40000000
#define PHYS_SDRAM_0			CONFIG_SYS_SDRAM_BASE
#define PHYS_SDRAM_0_SIZE		0x80000000 /* 2 GiB */

#define CONFIG_SYS_TEXT_BASE		0x42c00000
#define CONFIG_SYS_LOAD_ADDR		0x41000000
#define CONFIG_SYS_MALLOC_LEN		(CONFIG_ENV_SIZE + (64 << 20))

#define CONFIG_SYS_TIMER_COUNTER	0xc0017040	/* TCNTO4 */

#endif	/* __CONFIG_H */
