#
# (C) Copyright 2017 Andre Przywara <andre.przywara@arm.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	:= board.o
obj-$(CONFIG_ARM64)     += mmu-arm64.o
obj-y += ../cpu/armv7/s5p-common/timer.o
obj-y += ../cpu/armv7/s5p-common/pwm.o
