# SPDX-License-Identifier: GPL-2.0+

obj-$(CONFIG_DRAM_SUN8I_R528) += dram_sun20i_d1.o
obj-$(CONFIG_DRAM_SUN8I_R528) += dram_timings/d1_ddrx.o

obj-$(CONFIG_DRAM_SUN50I_H616) += dram_sun20i_d1.o
obj-$(CONFIG_DRAM_SUN50I_H616) += dram_timings/d1_ddrx.o

obj-$(CONFIG_MACH_SUN8I_H3) += dram_sun20i_d1.o
obj-$(CONFIG_MACH_SUN8I_H3) += dram_timings/d1_ddrx.o
